elite_dangerous:
  arguments: ''
  auto_launch: false
  delay: ''
  path: ''
general:
  auto_tray: false
  journal_path: ''
rich_presence:
  cmdr: true
  gamemode: true
  location: true
  multicrew_mode: true
  multicrew_size: true
  power: false
  ship_icon: true
  ship_text: false
  time_elapsed: true
