// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current activity status in the game
 */
export type ActivityStatus = "Launcher" | "MainMenu" | "Docked" | "NormalSpace" | "Supercruise" | "Landed" | "InSrv" | "OnFootStation" | "OnFootPlanet";
