// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiscordRichPresenceFields = { commander: boolean, superpower: boolean, location: boolean, gamemode: boolean, multicrew_mode: boolean, multicrew_size: boolean, time_elapsed: boolean, ship_icon: boolean, ship_text: boolean, };
