// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameStatus } from "./GameStatus";

export type GameProcessInfo = { status: GameStatus, 
/**
 * Process ID of the game (if running)
 */
game_pid: number | null, 
/**
 * Process ID of the launcher (if running)
 */
launcher_pid: number | null, 
/**
 * Start time of the game process (Unix timestamp in seconds)
 */
game_start_time: bigint | null, };
