// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityStatus } from "./ActivityStatus";

/**
 * Current game state tracked from journal events
 */
export type GameState = { 
/**
 * Commander name
 */
commander: string | null, 
/**
 * Current star system
 */
star_system: string | null, 
/**
 * Current body (planet/station/etc)
 */
body: string | null, 
/**
 * Current station name (if docked)
 */
station: string | null, 
/**
 * Current ship type (internal name like "sidewinder")
 */
ship: string | null, 
/**
 * Current ship name (player-given name)
 */
ship_name: string | null, 
/**
 * Current game mode (Solo, Open, Private)
 */
game_mode: string | null, 
/**
 * Current activity status
 */
status: ActivityStatus, 
/**
 * Whether in a taxi (Apex shuttle)
 */
in_taxi: boolean, 
/**
 * Whether in multicrew
 */
in_multicrew: boolean, 
/**
 * Current Power (Powerplay)
 */
power: string | null, 
/**
 * Session start timestamp (Unix seconds)
 */
session_start: bigint | null, 
/**
 * Whether this is a legacy (Horizons 3.8) session
 */
is_legacy: boolean, };
