// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JournalFileInfo } from "./JournalFileInfo";
import type { ParseResult } from "./ParseResult";

/**
 * Result of reading a journal file
 */
export type JournalReadResult = { 
/**
 * The file that was read
 */
file: JournalFileInfo | null, 
/**
 * Events from the file (successful parses only)
 */
events: Array<ParseResult>, 
/**
 * Total number of lines
 */
total_lines: number, 
/**
 * Number of successfully parsed events
 */
success_count: number, 
/**
 * Number of unknown events
 */
unknown_count: number, 
/**
 * Number of parse errors
 */
error_count: number, 
/**
 * Error message if reading failed
 */
error: string | null, };
