// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JournalFileInfo } from "./JournalFileInfo";

/**
 * Result of journal discovery and reading
 */
export type JournalInfo = { 
/**
 * Whether the journal directory was found
 */
directory_found: boolean, 
/**
 * The journal directory path
 */
journal_directory: string | null, 
/**
 * List of discovered journal files (newest first)
 */
files: Array<JournalFileInfo>, 
/**
 * Error message if any
 */
error: string | null, };
