// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a discovered journal file
 */
export type JournalFileInfo = { 
/**
 * Full path to the journal file
 */
path: string, 
/**
 * Filename without directory
 */
filename: string, 
/**
 * Timestamp extracted from filename
 */
timestamp: bigint | null, 
/**
 * Part number (for multi-part journals)
 */
part: number | null, };
