// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JournalEvent } from "./JournalEvent";

/**
 * Result of parsing a single journal line
 */
export type ParseResult = { 
/**
 * The parsed event, if successful
 */
event: JournalEvent | null, 
/**
 * The raw event type name (useful for unknown events)
 */
event_type: string | null, 
/**
 * Error message if parsing failed
 */
error: string | null, 
/**
 * The raw JSON line (useful for debugging)
 */
raw: string | null, };
