// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parser statistics
 */
export type ParserStats = { success_count: number, unknown_count: number, error_count: number, };
