// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiscordRichPresenceFields } from "./DiscordRichPresenceFields";
import type { ExecutablePath } from "./ExecutablePath";
import type { LaunchMethod } from "./LaunchMethod";
import type { LogLevel } from "./LogLevel";

export type Settings = { start_to_tray: boolean, close_with_game: boolean, check_for_updates: boolean, start_app_with_system: boolean, game_directory: string | null, log_level: LogLevel, discord_fields: DiscordRichPresenceFields, launch_method: LaunchMethod, executable_path: ExecutablePath, launch_arguments: string, start_game_with_app: boolean, };
